### ISSUE TITLE
Python 2.7 dependency issue

### ISSUE THREAD

**Issue by JaimePSantos** [josh146/pyctqw#2]
Hello, I'm not sure if this is supported anymore, but I'm a PHD student working with continuous-time quantum walks and I was very interested in experimenting with your simulator.

I was able to install every dependency yesterday with python 3, however when I tried to import the package in the notebook, it said that the module ctqw.py was not found.

That's when i realized that pyCTQW was written in python 2.7, however i got the following error installing mpi4py 
`ERROR: Could not build wheels for mpi4py which use PEP 517 and cannot be installed directly`

I then further noticed the depreaction warning
`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
`

And this is why i am opening this issue. Is it possible to use your simulator with python 3? If not, is there a way to install these dependencies?

Thank you!

**Comment by JaimePSantos** [comment]
I'll leave the result of running `python setup.py build` with python 3 below

```
running build
running config_cc
INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
INFO: build_src
INFO: building extension "libpyctqw_MPI" sources
INFO: f2py options: ['--quiet']
INFO:   adding 'build/src.linux-x86_64-3.9/build/src.linux-x86_64-3.9/src/fortranobject.c' to sources.
INFO:   adding 'build/src.linux-x86_64-3.9/build/src.linux-x86_64-3.9/src' to include_dirs.
INFO:   adding 'build/src.linux-x86_64-3.9/src/libpyctqw_MPI-f2pywrappers2.f90' to sources.
INFO: build_src: building npy-pkg config files
running build_py
running build_ext
INFO: customize UnixCCompiler
INFO: C compiler: mpicc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-FZ7wim/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-FZ7wim/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

creating /tmp/tmpiofqyls1/tmp
creating /tmp/tmpiofqyls1/tmp/tmpiofqyls1
INFO: compile options: '-MMD -MF /tmp/tmpiofqyls1/file.c.d -c'
INFO: mpicc: /tmp/tmpiofqyls1/file.c
INFO: customize UnixCCompiler using build_ext
INFO: CCompilerOpt.__init__[773] : load cache from file -> /home/jaime/Programming/pyctqw/build/temp.linux-x86_64-3.9/ccompiler_opt_cache_ext.py
INFO: CCompilerOpt.__init__[784] : hit the file cache
INFO: get_default_fcompiler: matching types: '['arm', 'gnu95', 'intel', 'lahey', 'pg', 'nv', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor', 'fujitsu']'
INFO: customize ArmFlangCompiler
INFO: Found executable /usr/bin/mpif90
WARN: Could not locate executable armflang
WARN: arm: no Fortran 77 compiler found
Traceback (most recent call last):
  File "/home/jaime/Programming/pyctqw/setup.py", line 184, in <module>
    run_setup()
  File "/home/jaime/Programming/pyctqw/setup.py", line 176, in run_setup
    setup(
  File "/home/jaime/Programming/pyctqw/py3venv/lib/python3.9/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/home/jaime/Programming/pyctqw/py3venv/lib/python3.9/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jaime/Programming/pyctqw/py3venv/lib/python3.9/site-packages/numpy/distutils/command/build.py", line 61, in run
    old_build.run(self)
  File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jaime/Programming/pyctqw/py3venv/lib/python3.9/site-packages/numpy/distutils/command/build_ext.py", line 272, in run
    self._f77_compiler = new_fcompiler(compiler=self.fcompiler,
  File "/home/jaime/Programming/pyctqw/py3venv/lib/python3.9/site-packages/numpy/distutils/fcompiler/__init__.py", line 880, in new_fcompiler
    compiler = get_default_fcompiler(plat, requiref90=requiref90,
  File "/home/jaime/Programming/pyctqw/py3venv/lib/python3.9/site-packages/numpy/distutils/fcompiler/__init__.py", line 851, in get_default_fcompiler
    compiler_type =  _find_existing_fcompiler(matching_compiler_types,
  File "/home/jaime/Programming/pyctqw/py3venv/lib/python3.9/site-packages/numpy/distutils/fcompiler/__init__.py", line 802, in _find_existing_fcompiler
    c.customize(dist)
  File "/home/jaime/Programming/pyctqw/py3venv/lib/python3.9/site-packages/numpy/distutils/fcompiler/__init__.py", line 542, in customize
    self.set_library_dirs(self.get_library_dirs())
  File "/home/jaime/Programming/pyctqw/py3venv/lib/python3.9/site-packages/numpy/distutils/fcompiler/arm.py", line 44, in get_library_dirs
    flang_dir = dirname(self.executables['compiler_f77'][0])
TypeError: 'NoneType' object is not subscriptable
INFO: 
########### EXT COMPILER OPTIMIZATION ###########
INFO: Platform      : 
  Architecture: x64
  Compiler    : icc

CPU baseline  : 
  Requested   : 'min'
  Enabled     : SSE SSE2 SSE3
  Flags       : -msse -msse2 -msse3
  Extra checks: none

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41
  Generated   : none
INFO: CCompilerOpt.cache_flush[817] : write cache to path -> /home/jaime/Programming/pyctqw/build/temp.linux-x86_64-3.9/ccompiler_opt_cache_ext.py

```

**Comment by josh146** [comment]
Hi @JaimePSantos! Unfortunately, as you note, this package was written with Python 2.7, and does not support Python 3. I'm unsure how much work is required to update it to support Python 3, but it could be quite a lot judging from the traceback above.

If you are using Anaconda, I recommend trying an Python 2.7 environment:

```python
conda create --name py2 python=2.7
```

and, within this environment, installing pyCTQW. Let me know how it goes!

**Comment by JaimePSantos** [comment]
Thanks for the quick reply!
I did manage to make some progress, conda managed to install some of the needed dependencies.
However, now I am having trouble with the Fortran compiler:

```
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "libpyctqw_MPI" sources
f2py options: ['--quiet']
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src' to include_dirs.
  adding 'build/src.linux-x86_64-2.7/src/libpyctqw_MPI-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
C compiler: mpicc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating /tmp/tmpfmWhS8/tmp
creating /tmp/tmpfmWhS8/tmp/tmpfmWhS8
compile options: '-MMD -MF /tmp/tmpfmWhS8/file.c.d -c'
mpicc: /tmp/tmpfmWhS8/file.c
/home/jaime/anaconda3/envs/py2/bin/mpicc: line 301: x86_64-conda_cos6-linux-gnu-cc: command not found
/home/jaime/anaconda3/envs/py2/bin/mpicc: line 301: x86_64-conda_cos6-linux-gnu-cc: command not found
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /home/jaime/anaconda3/envs/py2/bin/mpif90
Could not locate executable <F90> mpif90
Found executable /usr/bin/gfortran
Could not locate executable /usr/bin/gfortran mpif90
customize IntelFCompiler
Could not locate executable ifort
Could not locate executable ifc
customize LaheyFCompiler
Could not locate executable lf95
lahey: no Fortran 77 compiler found
Could not locate executable lf95 mpif90
lahey: no Fortran 77 compiler found
customize PGroupFCompiler
Could not locate executable pgfortran
pg: no Fortran 77 compiler found
Could not locate executable pgfortran mpif90
pg: no Fortran 77 compiler found
customize AbsoftFCompiler
Found executable /usr/bin/f77
customize NAGFCompiler
Found executable /usr/bin/f95
customize VastFCompiler
customize CompaqFCompiler
Could not locate executable fort
compaq: no Fortran 77 compiler found
compaq: no Fortran 77 compiler found
customize IntelItaniumFCompiler
Could not locate executable efort
Could not locate executable efc
customize IntelEM64TFCompiler
customize GnuFCompiler
Could not locate executable g77
gnu: no Fortran 90 compiler found
Could not locate executable  mpif90
gnu: no Fortran 90 compiler found
Could not locate executable /usr/bin/f77 mpif90
customize G95FCompiler
Could not locate executable g95
g95: no Fortran 77 compiler found
g95: no Fortran 77 compiler found
customize PathScaleFCompiler
Could not locate executable pathf95
pathf95: no Fortran 77 compiler found
Could not locate executable pathf95 mpif90
pathf95: no Fortran 77 compiler found
customize NAGFORCompiler
Could not locate executable nagfor
nagfor: no Fortran 77 compiler found
Could not locate executable nagfor mpif90
nagfor: no Fortran 77 compiler found
don't know how to compile Fortran code on platform 'posix'
warning: build_ext: f77_compiler=None is not available.

building 'libpyctqw_MPI' extension
error: extension 'libpyctqw_MPI' has Fortran sources but no Fortran compiler found
```

The output of running `gfortran --version` is 
```
GNU Fortran (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Any idea why the setup cannot find the compiler?
Thanks!


**Update:**

Managed to make a little more progress by installing both gcc and fortran-compiler through conda, this is now the output of setup.py build 
```
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "libpyctqw_MPI" sources
f2py options: ['--quiet']
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src' to include_dirs.
  adding 'build/src.linux-x86_64-2.7/src/libpyctqw_MPI-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
C compiler: mpicc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -D_FORTIFY_SOURCE=2 -O2 -fPIC

creating /tmp/tmpHAjYMk/tmp
creating /tmp/tmpHAjYMk/tmp/tmpHAjYMk
compile options: '-MMD -MF /tmp/tmpHAjYMk/file.c.d -c'
mpicc: /tmp/tmpHAjYMk/file.c
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /home/jaime/anaconda3/envs/py2/bin/mpif90
Could not locate executable <F90> mpif90
Found executable /home/jaime/anaconda3/envs/py2/bin/gfortran
Found executable /home/jaime/anaconda3/envs/py2/bin/x86_64-conda_cos6-linux-gnu-ld
Found executable /home/jaime/anaconda3/envs/py2/bin/x86_64-conda_cos6-linux-gnu-ar
Found executable /home/jaime/anaconda3/envs/py2/bin/x86_64-conda_cos6-linux-gnu-ranlib
Could not locate executable /home/jaime/anaconda3/envs/py2/bin/gfortran mpif90
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building 'libpyctqw_MPI' extension
compiling C sources
C compiler: mpicc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -D_FORTIFY_SOURCE=2 -O2 -fPIC

creating build/temp.linux-x86_64-2.7/build
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src
compile options: '-I/home/jaime/anaconda3/envs/py2/lib/petsc/arch-python-linux-x86_64/include -I/home/jaime/anaconda3/envs/py2/lib/petsc/include -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/petsc4py/include -I/home/jaime/anaconda3/envs/py2/lib/slepc-3.16.1/arch-python-linux-x86_64/include -I/home/jaime/anaconda3/envs/py2/lib/slepc-3.16.1/include -I. -Ibuild/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include -I/home/jaime/anaconda3/envs/py2/include/python2.7 -c'
mpicc: build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/fortranobject.c
mpicc: build/src.linux-x86_64-2.7/src/libpyctqw_MPImodule.c
In file included from /home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                 from /home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/fortranobject.h:13,
                 from build/src.linux-x86_64-2.7/src/libpyctqw_MPImodule.c:16:
/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
build/src.linux-x86_64-2.7/src/libpyctqw_MPImodule.c:151:12: warning: 'f2py_size' defined but not used [-Wunused-function]
 static int f2py_size(PyArrayObject* var, ...)
            ^~~~~~~~~
In file included from /home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                 from /home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/fortranobject.h:13,
                 from build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/fortranobject.c:2:
/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
compiling Fortran 90 module sources
Fortran f77 compiler: /home/jaime/anaconda3/envs/py2/bin/mpif90 -Wall -g -ffixed-form -fno-second-underscore -fPIC -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -O3 -funroll-loops
Fortran f90 compiler: mpif90 -Wall -g -fno-second-underscore -fPIC -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -O3 -funroll-loops
Fortran fix compiler: mpif90 -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -O3 -funroll-loops
creating build/temp.linux-x86_64-2.7/src
compile options: '-I/home/jaime/anaconda3/envs/py2/lib/petsc/arch-python-linux-x86_64/include -I/home/jaime/anaconda3/envs/py2/lib/petsc/include -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/petsc4py/include -I/home/jaime/anaconda3/envs/py2/lib/slepc-3.16.1/arch-python-linux-x86_64/include -I/home/jaime/anaconda3/envs/py2/lib/slepc-3.16.1/include -I. -Ibuild/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include -I/home/jaime/anaconda3/envs/py2/include/python2.7 -c'
extra options: '-Jbuild/temp.linux-x86_64-2.7/ -Ibuild/temp.linux-x86_64-2.7/'
extra f90 options: '-Wno-unused-variable -Wno-conversion -Wno-unused-dummy-argument'
mpif90:f90: ./src/ctqwMPI.F90
./src/ctqwMPI.F90:52:2:

 #include <finclude/petscvec.h90>
  1~~~~~~~~~~~~~~~~~
Fatal Error: finclude/petsc.h: No such file or directory
compilation terminated.
./src/ctqwMPI.F90:52:2:

 #include <finclude/petscvec.h90>
  1~~~~~~~~~~~~~~~~~
Fatal Error: finclude/petsc.h: No such file or directory
compilation terminated.
error: Command "mpif90 -Wall -g -fno-second-underscore -fPIC -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -O3 -funroll-loops -I/home/jaime/anaconda3/envs/py2/lib/petsc/arch-python-linux-x86_64/include -I/home/jaime/anaconda3/envs/py2/lib/petsc/include -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/petsc4py/include -I/home/jaime/anaconda3/envs/py2/lib/slepc-3.16.1/arch-python-linux-x86_64/include -I/home/jaime/anaconda3/envs/py2/lib/slepc-3.16.1/include -I. -Ibuild/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include -I/home/jaime/anaconda3/envs/py2/include/python2.7 -c -c ./src/ctqwMPI.F90 -o build/temp.linux-x86_64-2.7/src/ctqwMPI.o -Jbuild/temp.linux-x86_64-2.7/ -Ibuild/temp.linux-x86_64-2.7/ -Wno-unused-variable -Wno-conversion -Wno-unused-dummy-argument" failed with exit status 1

```

**Comment by josh146** [comment]
@JaimePSantos is it possible to also install PETSc and SLEPc via Conda?

**Comment by JaimePSantos** [comment]
Hi @josh146, I've just tried installing everything through conda following these steps:

1. `conda create --name py2 python=2.7`
2. `conda install -c conda-forge numpy`
3. `conda install -c conda-forge mpi4py`
4. `conda install -c conda-forge petsc`
5. `conda install -c conda-forge petsc4py`
6. `conda install -c conda-forge slepc`
7. `conda install -c conda-forge gcc`
8. `conda install -c conda-forge gfortran=8.5.0`
9. `export PETSC_DIR=/home/jaime/anaconda3/pkgs/petsc-3.7.2-blas_openblas_0`
10. `export SLEPC_DIR=/home/jaime/anaconda3/pkgs/slepc-3.7.4-0`
11. `export PETSC_ARCH=arch-python-linux-x86_64`

And the result of building setup.py is 

```
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "libpyctqw_MPI" sources
f2py options: ['--quiet']
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src' to include_dirs.
  adding 'build/src.linux-x86_64-2.7/src/libpyctqw_MPI-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
C compiler: mpicc -fno-strict-aliasing -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jaime/anaconda3/envs/py2/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jaime/anaconda3/envs/py2/include -fPIC

creating /tmp/tmpF7Eq9f/tmp
creating /tmp/tmpF7Eq9f/tmp/tmpF7Eq9f
compile options: '-MMD -MF /tmp/tmpF7Eq9f/file.c.d -c'
mpicc: /tmp/tmpF7Eq9f/file.c
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /home/jaime/anaconda3/envs/py2/bin/mpif90
Found executable /home/jaime/anaconda3/envs/py2/bin/x86_64-conda-linux-gnu-gfortran
Could not locate executable <F90> mpif90
Found executable /home/jaime/anaconda3/envs/py2/bin/gfortran
Found executable /home/jaime/anaconda3/envs/py2/bin/x86_64-conda-linux-gnu-ld
Found executable /home/jaime/anaconda3/envs/py2/bin/x86_64-conda-linux-gnu-ar
Found executable /home/jaime/anaconda3/envs/py2/bin/x86_64-conda-linux-gnu-ranlib
Could not locate executable /home/jaime/anaconda3/envs/py2/bin/gfortran mpif90
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building 'libpyctqw_MPI' extension
compiling C sources
C compiler: mpicc -fno-strict-aliasing -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jaime/anaconda3/envs/py2/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jaime/anaconda3/envs/py2/include -fPIC

compile options: '-I/home/jaime/anaconda3/pkgs/petsc-3.7.2-blas_openblas_0/include -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/petsc4py/include -I/home/jaime/anaconda3/pkgs/slepc-3.7.4-0/include -I. -Ibuild/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include -I/home/jaime/anaconda3/envs/py2/include/python2.7 -c'
compiling Fortran 90 module sources
Fortran f77 compiler: /home/jaime/anaconda3/envs/py2/bin/x86_64-conda-linux-gnu-gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jaime/anaconda3/envs/py2/include -O3 -funroll-loops
Fortran f90 compiler: mpif90 -Wall -g -fno-second-underscore -fPIC -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jaime/anaconda3/envs/py2/include -O3 -funroll-loops
Fortran fix compiler: mpif90 -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jaime/anaconda3/envs/py2/include -O3 -funroll-loops
compile options: '-I/home/jaime/anaconda3/pkgs/petsc-3.7.2-blas_openblas_0/include -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/petsc4py/include -I/home/jaime/anaconda3/pkgs/slepc-3.7.4-0/include -I. -Ibuild/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include -I/home/jaime/anaconda3/envs/py2/include/python2.7 -c'
extra options: '-Jbuild/temp.linux-x86_64-2.7/ -Ibuild/temp.linux-x86_64-2.7/'
extra f90 options: '-Wno-unused-variable -Wno-conversion -Wno-unused-dummy-argument'
mpif90:f90: ./src/ctqwMPI.F90
./src/ctqwMPI.F90:52:2:

 #include <finclude/petscvec.h90>
  1~~~~~~~~~~~~~~~~~
Fatal Error: finclude/petsc.h: No such file or directory
compilation terminated.
./src/ctqwMPI.F90:52:2:

 #include <finclude/petscvec.h90>
  1~~~~~~~~~~~~~~~~~
Fatal Error: finclude/petsc.h: No such file or directory
compilation terminated.
error: Command "mpif90 -Wall -g -fno-second-underscore -fPIC -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jaime/anaconda3/envs/py2/include -O3 -funroll-loops -I/home/jaime/anaconda3/pkgs/petsc-3.7.2-blas_openblas_0/include -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/petsc4py/include -I/home/jaime/anaconda3/pkgs/slepc-3.7.4-0/include -I. -Ibuild/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src -I/home/jaime/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include -I/home/jaime/anaconda3/envs/py2/include/python2.7 -c -c ./src/ctqwMPI.F90 -o build/temp.linux-x86_64-2.7/src/ctqwMPI.o -Jbuild/temp.linux-x86_64-2.7/ -Ibuild/temp.linux-x86_64-2.7/ -Wno-unused-variable -Wno-conversion -Wno-unused-dummy-argument" failed with exit status 1
```


Which I believe is the same as in the [previous](https://github.com/josh146/pyctqw/issues/2#issuecomment-1013929051) comment, with exception to petsc and slepc paths. 
Any ideas as to what might be causing this? Am I exporting the wrongs paths?
Thank you very much for your time!

**Comment by josh146** [comment]
Hi @JaimePSantos! Unfortunately I'm not too sure here, it has been a long time since I have used/installed PETSc and SLEPc, and no longer remember how I installed it these years ago!

The best place to ask might be on the Conda Forge github?

**Comment by JaimePSantos** [comment]
No problem! 
I'll look around some more and I'll post here if I manage to solve this.
Thank you!
